### PR TITLE
Minor bug fix for mobile on boarding

### LINKED ISSUE #6997: Mobile: Next button causes next slide to be hidden from view
# _BUG_

---
#### Current Behavior

On mobile, when clicking 'next' on slide one, the user is brought down to the header image and will only see screen two if they choose to scroll back up. 
#### Desired Behavior

After clicking 'next' on slide one, a user should see screen two of onboarding without having to look for it. 
#### Steps to Replicate

1) Sign up for any campaign on mobile
2) Click 'next' on screen one and observe
#### Why This Matters

This creates a jolty experience and makes it difficult for mobile users to have a full onboarding experience. 
#### Browsers / OS

Safari & Chrome on iOS

### PR DESCRIPTION
**Pull request by itsjoekent**
#### What's this PR do?
- Forces the browser to (0, 0) when you change slides in onboarding. 
#### How should this be reviewed?

sep-14-2016 13-46-48
#### Any background context you want to provide?

no
#### Relevant tickets

Fixes #6997 
#### Checklist
- [ ] Tested on staging.

### CODE REVIEW

File: lib/themes/dosomething/paraneue_dosomething/js/components/Slideshow.js [hunk 1]
```diff
@@ -20,13 +20,19 @@ class Slideshow extends React.Component {
     this.moveForward = this.moveForward.bind(this);
   }
 
+  move() {
```
Comment (weerd) [inline lib/themes/dosomething/paraneue_dosomething/js/components/Slideshow.js]: Not a good name for this method... maybe `reset`? `recenter`?

Comment (itsjoekent) [reply lib/themes/dosomething/paraneue_dosomething/js/components/Slideshow.js]: I kinda like realign?

Comment (itsjoekent) [reply lib/themes/dosomething/paraneue_dosomething/js/components/Slideshow.js]: center feels like doing a 50% kinda thing

**Comment by weerd** [comment]
Do we know what is actually causing the issue? I feel this is a patch to cover the actual problem? Why is it dropping to the header?

File: lib/themes/dosomething/paraneue_dosomething/js/components/Slideshow.js (hunk 1 above)
Comment (weerd) [reply lib/themes/dosomething/paraneue_dosomething/js/components/Slideshow.js]: Sounds good! `realign()` it is!

**Comment by itsjoekent** [comment]
@weerd good to go?

**Comment by weerd** [comment]
¡OLÉ! :sheep: it!

Just wanted to note here, that this may be an issue being cause because currently it seems the way we built it, React is being forced to re-render all 3 slides each time the **prev** or **next** buttons are pressed. This is not ideal. Something we may want to look at in the future.

File: lib/themes/dosomething/paraneue_dosomething/js/components/Slideshow.js [hunk 2]
```diff
@@ -20,13 +20,19 @@ class Slideshow extends React.Component {
     this.moveForward = this.moveForward.bind(this);
   }
 
+  realign() {
+    window.scrollTo(0, 0);
```
Comment (itsjoekent) [inline lib/themes/dosomething/paraneue_dosomething/js/components/Slideshow.js:24]: this is a test github review

Comment (itsjoekent) [reply lib/themes/dosomething/paraneue_dosomething/js/components/Slideshow.js:24]: test

Comment (itsjoekent) [inline lib/themes/dosomething/paraneue_dosomething/js/components/Slideshow.js:24]: this is another conversation

File: lib/themes/dosomething/paraneue_dosomething/js/components/Slideshow.js [hunk 3]
```diff
@@ -20,13 +20,19 @@ class Slideshow extends React.Component {
...
+  }
+
```
Comment (itsjoekent) [inline lib/themes/dosomething/paraneue_dosomething/js/components/Slideshow.js:26]: this is a review comment

**Review by itsjoekent — COMMENTED** [review]
This is the review summary
