### PR TITLE
Runs bug

### LINKED ISSUE #6373: Runs param on /signups returns incorrect data with pagination
#### Current Behavior
- When using the runs param with `/signups`, each page returns same exact signup objects. This returns incorrect information - only values for one campaign run id are returned if you pass multiple ids in the run param e.g. https://www.dosomething.org/api/v1/signups?campaigns=362&runs=2341,5439
#### Desired Behavior
- Pagination should return different reportback objects on each page.
#### Steps to Replicate
- Hit https://www.dosomething.org/api/v1/signups?campaigns=362&runs=2341,5439 and click on `next_uri` link -  you'll see that the results are the same as the previous and next pages.
#### Why This Matters
- Incorrect data is being returned when using multiple campaign runs. 
- Pagination is broken.

### PR DESCRIPTION
**Pull request by chloealee**
#### What's this PR do?

Added missing `setOffset` to `ReportbackTransformer.php` and `SignupTransformer.php` to fix pagination issues. 

Updates `build` function in Signup.php to only return `drupal_id` - the rest of the user information gets filled in by [Northstar proxy](https://github.com/DoSomething/northstar/pull/343). 
#### How should this be manually tested?

Make sure that `prev_uri` and `next_uri` links return different data on each page for `/signups` and `/reportbacks`.
#### What are the relevant tickets?

Fixes #6373 
Refs #6372 - fixes pagination error for this issue.

### CODE REVIEW

File: lib/modules/dosomething/dosomething_signup/includes/Signup.php [hunk 1]
```diff
@@ -110,7 +110,7 @@ private function build($data) {
       'id' => isset($northstar_user) ? $northstar_user->id : $data->field_northstar_id_value,
       'first_name' => dosomething_helpers_extract_field_data($drupal_user->field_first_name),
       'last_initial' => $last_initial,
-      'photo' => dosomething_helpers_extract_field_data($drupal_user->photo),
+      'photo' => isset($drupal_user->picture) ? $drupal_user->picture : NULL,
```
Comment (aaronschachter) [inline lib/modules/dosomething/dosomething_signup/includes/Signup.php]: Question about this change -- for #mobile-app, we need the User's Northstar avatar, not their default Drupal User.picture property...

Comment (itsjoekent) [inline lib/modules/dosomething/dosomething_signup/includes/Signup.php]: We get the northstar object above this now but only for ppl that dont have a northstar ID saved in the DB.

Comment (chloealee) [inline lib/modules/dosomething/dosomething_signup/includes/Signup.php]: oooh so right - thanks for catching @aaronschachter! So should we always load the northstar user then?

Comment (itsjoekent) [inline lib/modules/dosomething/dosomething_signup/includes/Signup.php]: doing this has been under debate - mainly because when we're bulk fetching users it will take _forever_ to get a response back. debating the best way to handle this... @weerd ?

Comment (chloealee) [inline lib/modules/dosomething/dosomething_signup/includes/Signup.php]: or @deadlybutter, should we just change back to `'photo' => dosomething_helpers_isset($northstar_user, 'photo')` instead of your change [here](https://github.com/DoSomething/phoenix/commit/2a79a94b2e8760f5eba04576faa5b61099474385)?

Comment (itsjoekent) [inline lib/modules/dosomething/dosomething_signup/includes/Signup.php]: @chloealee no this wont work 100% of the time, northstar user is only created when we dont have the northstar ID saved in the database https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_signup/includes/Signup.php#L99

Comment (chloealee) [inline lib/modules/dosomething/dosomething_signup/includes/Signup.php]: ahh i see thanks @deadlybutter !

Comment (chloealee) [inline lib/modules/dosomething/dosomething_signup/includes/Signup.php]: discussion between @deadlybutter and I on slack [here](https://dosomething.slack.com/archives/phoenix/p1461004451000027). @weerd do you think it makes sense to always load the user object so we have access to the avatar?

Comment (itsjoekent) [inline lib/modules/dosomething/dosomething_signup/includes/Signup.php]: *only for requests with 1 user

Comment (weerd) [inline lib/modules/dosomething/dosomething_signup/includes/Signup.php]: Maybe that's something that Northstar could add when it's getting proxied. Kinda like how with Gladiator, we send the `/signups` request to Gladiator and it will convert all the NS IDs we pass to Phoenix IDs to send to Phoenix. So what could happen is NS receives the request to `/signups` proxies to Phoenix, when Phoenix sends it back to NS, it takes control and adds the NS avatar  info then, before proceeding with sending the full response back to client? Avoids having to request from NS only to then send back to NS anyways.... @DFurnes thoughts?

Comment (DFurnes) [inline lib/modules/dosomething/dosomething_signup/includes/Signup.php]: It's definitely a good short-term fix. I'd like to be able to remove those two proxy endpoints from Northstar sometime in the near-ish future though, and I worry a bit that this would be making them more tightly coupled. Not sure what a better solution is though. 😅

Comment (itsjoekent) [inline lib/modules/dosomething/dosomething_signup/includes/Signup.php]: removing the proxies would break gladiator, we dont have drupal id's

Comment (DFurnes) [inline lib/modules/dosomething/dosomething_signup/includes/Signup.php]: Yep, hence sometime in the near-ish future, rather than immediately and without warning. 😉 Once Phoenix has Northstar IDs in it though, that part of the proxy can be removed.

Comment (chloealee) [inline lib/modules/dosomething/dosomething_signup/includes/Signup.php]: @DFurnes @weerd I'm a little confused about how this would play out.
@weerd - you said "Kinda like how with Gladiator, we send the /signups request to Gladiator and it will convert all the NS IDs we pass to Phoenix IDs to send to Phoenix." - can you send me the code for this so I can see by example to wrap my head around?

Comment (DFurnes) [inline lib/modules/dosomething/dosomething_signup/includes/Signup.php]: @chloealee Here's the [`signups/` proxy route](https://github.com/DoSomething/northstar/blob/dev/app/Http/Controllers/SignupController.php#L32-L58) in Northstar.

I think @weerd's solution is a good fix for now, but I do want to think a bit on how we can better handle situations like this so we're not piping requests through an ever-growing number of services when we need info from multiple places.

Comment (weerd) [inline lib/modules/dosomething/dosomething_signup/includes/Signup.php]: Yeah, my main worry is having a bunchof back-and-forth API calls to grab all data and it totally killing the processing time due to all the HTTP requests. I'm also not 100% sure I know _what_ the user avatar is and how it differs from the profile picture (which I think was just used for MCC stuff)...

Comment (chloealee) [inline lib/modules/dosomething/dosomething_signup/includes/Signup.php]: thanks @DFurnes and @weerd ! Sorry for my confusion on my end but are the steps to take to also send back the NS avatar picture in the [proxy route](https://github.com/DoSomething/northstar/blob/dev/app/Http/Controllers/SignupController.php#L32-L58) and to call this in [Signup.php's `build` function](https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_signup/includes/Signup.php#L88)?

@weerd the avatar picture is confusing! It's the avatar picture on the mobile app that gets saved to aws. As I understand, on the site, the only people who have profile pictures are admins? cc @aaronschachter in case I got any of that incorrect.

Comment (DFurnes) [inline lib/modules/dosomething/dosomething_signup/includes/Signup.php]: @chloealee Yeah I think that's correct! I wonder if we could "merge" those two properties and just reformat the MCC campaign badge to use a rounded avatar instead...? It is pretty confusing to have both. 😕 

If we add the user property in the Northstar proxy, we can just remove the `$this->user` business in the `build` function and then "append" it to each signup in the result in the Northstar proxy method (since then it could happen as a single database query, rather than multiple HTTP requests).

Comment (chloealee) [inline lib/modules/dosomething/dosomething_signup/includes/Signup.php]: awesome, thanks for everyone's input! Talked more with @DFurnes in slack but for documentation, here's the plan: 
1. update the code in phoenix for approval
2. open a new issue in northstar to address changes (adding user info, including avatar to pass back) 
3. make a new pr with changes in northstar
4. once approved, merge northstar and deploy
5. merge phoenix changes and deploy

Comment (aaronschachter) [inline lib/modules/dosomething/dosomething_signup/includes/Signup.php]: Chiming in on Avatar vs Drupal user picture -- assuming nothing's changed over the past year or so -- yep the only place we use the Drupal `user.picture` is when we have a MCC - our staff uploads an image we prepare with the Member on a transparent background. Deprecating the Drupal `user.picture` would be ideal but likely requires tweaks to the Member Created designs... if we even use them anymore? 

`destroy` 🔥 🚒

Comment (weerd) [inline lib/modules/dosomething/dosomething_signup/includes/Signup.php]: Awesome! Sounds good to me @chloealee I like this direction :)

**Comment by chloealee** [comment]
@weerd @DFurnes Working through this more, I think we'll need to still keep the `$this->user` business on the phoenix side because otherwise, in ns, we don't have access to the user if it's not returned in the results here. 

In ns, I'm taking the results from hitting the phoenix endpoint, iterating through each one to get the user, find the user avatar image and append it to the user object. 

Just want to run by you both quickly to make sure I'm not going down a rabbit hole! Please let me know if this makes sense to you both or if I'm overlooking something obvious!

**Comment by DFurnes** [comment]
@chloealee Ahhhh, yeah that makes sense. It may be best to remove all the fields aside from `drupal_id` then so that it's more clear that the user content gets re-written elsewhere?

**Comment by chloealee** [comment]
@DFurnes smart - that makes sense!

**Comment by weerd** [comment]
Yep yep! Defs don't remove the `user` object on the Phoenix side. There's other things that need it, etc. Just getting rid of the `user->photo` or whatever should be fine, and then like you mention, having NS add that data and property :)

**Comment by DFurnes** [comment]
@weerd Do we have any services that aren't using the Northstar proxy for those endpoints? If not, I'd make a vote for _not_ including those fields in the original Phoenix response and then replacing them on Northstar just so it's clear that they're coming from elsewhere.

**Comment by weerd** [comment]
@DFurnes I don't think there's any service using `/signups` without going via the proxy. 

Which fields do you mean? I thought it's just the photo related one?

**Comment by chloealee** [comment]
@weerd the `user` object also returns  `first_name`, `last_initial`, and `country` in addition to `photo` and `id`. I think @DFurnes is suggesting to leave `id` (which I believe is the northstar id) and then just append all the rest into the user object coming from NS.

**Comment by weerd** [comment]
Oh gotcha! Yep yep. Thanks for clarifying @chloealee 💃

**Comment by DFurnes** [comment]
> I think @DFurnes is suggesting to leave id (which I believe is the northstar id) and then just append all the rest into the user object coming from NS.

Yep! The reason I say that is so that there aren't two separate scenarios where `first_name` (or other fields) could be filled in with potentially different data (depending on where you hit the endpoint from).

If we only return `user: { drupal_id: 123456 }` on the response, I feel like it makes it a bit more clear that it's a "placeholder" for someone else down the line to fill-in the real user data in the response.

**Comment by weerd** [comment]
Cool. We'll likely need to update other endpoints that pull in the user info too. It'll probs just be an update to the user transformer :)

**Comment by chloealee** [comment]
@weerd  - @DFurnes helped to refactor this to make sure nothing breaks! We just added `drupal_id` in the `transformUser` function in the Transformer. This way, nothing should change elsewhere and data just gets overridden by the northstar proxy. 

This is all set for review whenever you get a chance @weerd !

**Comment by weerd** [comment]
Right-on! Checking now 💃

File: lib/modules/dosomething/dosomething_signup/includes/Signup.php [hunk 2]
```diff
@@ -89,29 +89,8 @@ private function build($data) {
...
-        user_save($drupal_user, ['field_northstar_id' => [LANGUAGE_NONE => [0 => ['value' => $northstar_user->id]]]]);
-      }
-    }
-
-    $last_initial = substr(dosomething_helpers_extract_field_data($drupal_user->field_last_name), 0, 1);
-    if ($last_initial === FALSE) {
-      $last_initial = NULL;
-    }
-
     $this->user = [
```
Comment (weerd) [inline lib/modules/dosomething/dosomething_signup/includes/Signup.php:92]: Ok, so just to be sure on this (since Gladiator highly depends on this part at the moment), the response sends back to Northstar the drupal id, and Northstar figures out the rest to add the user info, etc?

Gonna cc @deadlybutter cause he worked on the above fix for Gladiator. Once this is merged we should definitely test out Gladiator QA w/ Phoenix Staging!

Comment (weerd) [inline lib/modules/dosomething/dosomething_signup/includes/Signup.php:92]: Also, this _only_ happens for when it's a NS proxied endpoint to Phoenix, correct?

Comment (itsjoekent) [inline lib/modules/dosomething/dosomething_signup/includes/Signup.php:92]: nearly had a heart attack, but read top of PR & now I get it haha

yar, lets test test test when this stuff gets deployed.

will deploying the northstar PR first break anything? feels safer to do that first to make sure everything works on that end, then deploy phoenix

Comment (DFurnes) [inline lib/modules/dosomething/dosomething_signup/includes/Signup.php:92]: Yep, so Phoenix would always return _just_ `drupal_id` for the user response since that's all it can reliably say about a user. And then for any requests going through the Northstar proxy, Northstar would add the relevant `first_name`, `last_initial`, etc etc to each `user` object.

Comment (weerd) [inline lib/modules/dosomething/dosomething_signup/includes/Signup.php:92]: ok, cause in the user transformer above, it's not _just_ returning the `drupal_id`, but other items as well: https://github.com/DoSomething/phoenix/pull/6381/files#diff-2f3c6ef3f5ca436621af7d7d225af381R454

Comment (DFurnes) [inline lib/modules/dosomething/dosomething_signup/includes/Signup.php:92]: @weerd Is that `transformUser` method used elsewhere? We should probably remove those fields if not.

Comment (weerd) [inline lib/modules/dosomething/dosomething_signup/includes/Signup.php:92]: Yeah, it's definitely used on other endpoints, like `/reportback` etc. Not just the `/signups` endpoint.

Comment (DFurnes) [inline lib/modules/dosomething/dosomething_signup/includes/Signup.php:92]: Mmmm, yeah! Let's not break those then. 😄

**Comment by chloealee** [comment]
@DFurnes @weerd quick q! Trying to test and debug this and I'm not sure it's actually getting sent through to NS when I thought it already was hooked up - where does the NS proxy connect/come into play here?

**Comment by DFurnes** [comment]
@chloealee Northstar is the "proxy" for the request –– so clients would make their request to Northstar (like `https://northstar.dosomething.org/v1/signups`) and then Northstar makes the corresponding Phoenix API request on their behalf (and makes any modifications before/after the request)!

So Phoenix never talks to Northstar here. :)

**Comment by chloealee** [comment]
@DFurnes oooohhh that makes so much more sense, thank you for clarifying that! That's why when `/signups` testing on dev.dosomething.org, all user info isn't fully returned - mystery solved! Thank you!

File: lib/modules/dosomething/dosomething_signup/includes/Signup.php [hunk 3]
```diff
@@ -89,28 +89,13 @@ private function build($data) {
...
-      'last_initial' => $last_initial,
-      'photo' => dosomething_helpers_extract_field_data($drupal_user->photo),
-      'country' => dosomething_helpers_extract_field_data($drupal_user->field_address),
+      'id' => NULL,
+      'drupal_id' => $data->uid,
+      'first_name' => NULL,
+      'last_initial' => NULL,
+      'photo' => NULL,
+      'country' => NULL,
     ];
```
Comment (chloealee) [inline lib/modules/dosomething/dosomething_signup/includes/Signup.php:94]: @weerd added these properties back in and set them to `NULL` to prevent errors in the db logs!

**Comment by chloealee** [comment]
@weerd going to merge the [NS code ](https://github.com/DoSomething/northstar/pull/343) and then after would love to merge this! I tested with `/reportbacks?load_user=true` along with testing pagination and nothing broke on my local! Would you mind taking a final look for merge?

File: lib/modules/dosomething/dosomething_signup/includes/Signup.php (hunk 3 above)
Comment (weerd) [inline lib/modules/dosomething/dosomething_signup/includes/Signup.php:94]: Cool. Are they always `null` now? When do they get populated? Is there a reason for changing from the above if those items existed? Been a few days since I looked at this and brain is kinda fuzzy on it.

Comment (chloealee) [inline lib/modules/dosomething/dosomething_signup/includes/Signup.php:94]: These get populated from the [NS proxy](https://github.com/DoSomething/northstar/pull/343). I set them to `NULL` because otherwise it throws an error in the db logs saying `Notice: Undefined property: stdClass::$country in Transformer->transformUser() (line 459 of /var/www/dev.dosomething.org/lib/modules/dosomething/dosomething_api/includes/Transformer.php).` for each of these properties.

Comment (weerd) [inline lib/modules/dosomething/dosomething_signup/includes/Signup.php:94]: Gotcha. An alternative option could be to use the `dosomething_helpers_isset()` function in the actual [`transformUser()`](https://github.com/DoSomething/phoenix/blob/dev/lib/modules/dosomething/dosomething_api/includes/Transformer.php#L452)

Not a huge deal now, but it's something to consider if `Signup` class is used internally for stuff and doesn't call out to NS for DS Web App stuff. (Kinda like the `Campaign` class does). I know it's not the case now, but could be in the future. Maybe it's worth adding a comment to note that and not necessarily worry about changing it now.

Comment (chloealee) [inline lib/modules/dosomething/dosomething_signup/includes/Signup.php:94]: ah that is smart! I can make that change now to the `transformUser()` function now so we don't have to worry about it later :)

**Comment by weerd** [comment]
¡OLÉ!
:sheep: it!
