### PR TITLE
fixes invalid argument in foreach block for mobile app date

### LINKED ISSUE #4763: Invalid argument supplied for foreach() in Campaign class
When extracting Mobile App start and end dates, there is a bug when trying to pass through `null` through foreach() block if no dates are set. 

```
Warning: Invalid argument supplied for foreach() in Campaign->getMobileAppDate() (line 379 of /var/www/staging.beta.dosomething.org/releases/20150728191855/lib/modules/dosomething/dosomething_campaign/includes/Campaign.php).
```

### PR DESCRIPTION
**Pull request by chloealee**
Refs #4754 

Fixes #4763

### CODE REVIEW

File: lib/modules/dosomething/dosomething_campaign/includes/Campaign.php [hunk 1]
```diff
@@ -376,8 +376,12 @@ protected function getMobileAppDate() {
       $timing = [];
       $timing['dates'] = (dosomething_helpers_extract_field_data($this->node->field_mobile_app_date));
 
-      foreach ($timing['dates'] as $key => $date) {
-        $timing['dates'][$key] = dosomething_helpers_convert_date($date);
+      if ($timing['dates'] != null) {
```
Comment (angaither) [inline lib/modules/dosomething/dosomething_campaign/includes/Campaign.php]: does if(isset($timing['dates'])` work here, we tend to use that as the standard check

File: lib/modules/dosomething/dosomething_campaign/includes/Campaign.php [hunk 2]
```diff
@@ -376,8 +376,12 @@ protected function getMobileAppDate() {
...
+        foreach ($timing['dates'] as $key => $date) {
+          $timing['dates'][$key] = dosomething_helpers_convert_date($date);
+        }
+      } else {
+        $timing['dates'] === null;
```
Comment (angaither) [inline lib/modules/dosomething/dosomething_campaign/includes/Campaign.php]: when you're assigning a var, one `=` will do 
do you need this though, if it isn't set shouldn't it already be null?

**Comment by angaither** [comment]
Also, can you ref which issue this is fixing

File: lib/modules/dosomething/dosomething_campaign/includes/Campaign.php (hunk 1 above)
Comment (weerd) [inline lib/modules/dosomething/dosomething_campaign/includes/Campaign.php]: the method @angaither suggests, `isset()` will actually check if the variable is `null` or even exists. So it might be possible that the variable might not even exist (which is happening in the bug I'm working on right now), and `isset()` helps check for both scenarios :)

Comment (chloealee) [inline lib/modules/dosomething/dosomething_campaign/includes/Campaign.php]: ahhh got it - way more efficient! Will change it, thank you both!

File: lib/modules/dosomething/dosomething_campaign/includes/Campaign.php (hunk 2 above)
Comment (chloealee) [inline lib/modules/dosomething/dosomething_campaign/includes/Campaign.php]: true - I will delete!

**Comment by weerd** [comment]
:+1:

**Comment by angaither** [comment]
:+1:
