### PR TITLE
fixes reportback gallery view more link

### LINKED ISSUE #6257: Clicking view more on the report back gallery doesn't display more photos
#### Current Behavior
- Clicking view more on the reportback gallery of campaign causes an endless spinner and no additional photos to appear. Note: there are more than 6 approved/promoted reportbacks.
#### Desired Behavior
- Clicking view more will display the additional promoted/approved reportback images according to previously logic.
#### Steps to Replicate
- Sign up for https://thor.dosomething.org/us/campaigns/guns-out
- Go to the gallery
- Click view more
- Witness that no additional photos load
#### Why This Matters

Users consistently call out seeing other people doing the action as a motivating factor for them to take the action themselves. Also looks like no one is doing our new spotlight campaign which isn't true.
#### Relevant Screenshots + Links

https://thor.dosomething.org/us/campaigns/guns-out

image

image

cc: @angaither @weerd

### PR DESCRIPTION
**Pull request by chloealee**
#### What's this PR do?

Updates `Reportback.js` to reflect API updates made in #6223. 
#### How should this be manually tested?

Go to any campaign page and click on the view more link on the report back gallery to make sure more photos are loaded. 
#### What are the relevant tickets?

Fixes #6257

### CODE REVIEW

File: lib/modules/dosomething/dosomething_reportback/includes/ReportbackItem.php [hunk 1]
```diff
@@ -111,7 +111,7 @@ private function build($data, $full = false) {
     if ($full) {
       $northstar_response = dosomething_northstar_get_northstar_user($data->uid);
       $northstar_response = json_decode($northstar_response);
-
+
```
Comment (angaither) [inline lib/modules/dosomething/dosomething_reportback/includes/ReportbackItem.php]: you should remove this file from the changes
`git checkout HEAD --lib/modules/dosomething/dosomething_reportback/includes/ReportbackItem.php`

File: lib/themes/dosomething/paraneue_dosomething/js/reportback/Reportback.js [hunk 2]
```diff
@@ -251,7 +251,8 @@ define(function(require) {
           }
         }
       }).done(function (response) {
-        _this.apiUrl = response.pagination.next_uri || null;
+        _this.apiUrl = response.meta.pagination.links.next_uri || null;
+        console.log(response);
```
Comment (angaither) [inline lib/themes/dosomething/paraneue_dosomething/js/reportback/Reportback.js]: remove this

File: lib/modules/dosomething/dosomething_reportback/includes/ReportbackItem.php (hunk 1 above)
Comment (chloealee) [inline lib/modules/dosomething/dosomething_reportback/includes/ReportbackItem.php]: @angaither when I tried to do that, I got this error message: 

```
error: unknown option `lib/modules/dosomething/dosomething_reportback/includes/ReportbackItem.php'
usage: git checkout [<options>] <branch>
   or: git checkout [<options>] [<branch>] -- <file>...

    -q, --quiet           suppress progress reporting
    -b <branch>           create and checkout a new branch
    -B <branch>           create/reset and checkout a branch
    -l                    create reflog for new branch
    --detach              detach the HEAD at named commit
    -t, --track           set upstream info for new branch
    --orphan <new-branch>
                          new unparented branch
    -2, --ours            checkout our version for unmerged files
    -3, --theirs          checkout their version for unmerged files
    -f, --force           force checkout (throw away local modifications)
    -m, --merge           perform a 3-way merge with the new branch
    --overwrite-ignore    update ignored files (default)
    --conflict <style>    conflict style (merge or diff3)
    -p, --patch           select hunks interactively
    --ignore-skip-worktree-bits
                          do not limit pathspecs to sparse entries only
```

Comment (angaither) [inline lib/modules/dosomething/dosomething_reportback/includes/ReportbackItem.php]: @chloealee what directory are you in? it might be `../lib/etc/etc/`

Comment (chloealee) [inline lib/modules/dosomething/dosomething_reportback/includes/ReportbackItem.php]: @angaither hmm I was at the root `/dosomething-mount` and still getting that error

**Comment by angaither** [comment]
:+1:

**Comment by weerd** [comment]
:dancer: :dancers: :tada:
