### PR TITLE
Onboarding progress behavior and styles

### LINKED ISSUE #6717: ERROR in ./js/components/Onboarding.js
## _ERROR in ./js/components/Onboarding.js_

Since v2.6.46, there's an error in Prod Deploy log:
https://jenkins.dosomething.org/job/Deploy-Production/159/console 

```
ERROR in ./js/components/Onboarding.js
 DEBUG [d400b0d8]     Module not found: Error: Cannot resolve 'file' or 'directory' ./Carousel.js in /var/www/www.dosomething.org/releases/20160713164539/lib/themes/dosomething/paraneue_dosomething/js/components
 @ ./js/components/Onboarding.js 9:16-40
```

### PR DESCRIPTION
**Pull request by weerd**
#### What's this PR do?

This PR has some progress updates on the Onboarding feature. It provides updates to the React structure and functionality as well as setting up a good base for the initial styles.
#### How should this be reviewed?

Preview of current progress:
image
#### Relevant tickets

Fixes #6717
Refs #6682
#### Checklist
- [ ] Tested on staging.

---

@DFurnes

### CODE REVIEW

File: lib/themes/dosomething/paraneue_dosomething/js/components/ContextSlide.js [hunk 1]
```diff
@@ -11,9 +11,21 @@ class ContextSlide extends React.Component {
 
   render() {
     return (
-      <div className="carousel__slide">
-        <h1>{"Woohoo! You're signed up."}</h1>
-        <p>here is some text</p>
+      <div className="container slideshow__slide">
```
Comment (DFurnes) [inline lib/themes/dosomething/paraneue_dosomething/js/components/ContextSlide.js]: Having `slideshow__slide` here feels strange to me. Maybe this should be it's own BEM element, or the `slideshow__slide` should be applied as a wrapping container from the Slideshow component? (Not anything that's necessary to change for this PR, just thinking aloud).

File: lib/themes/dosomething/paraneue_dosomething/js/components/ContextSlide.js [hunk 2]
```diff
@@ -11,9 +11,21 @@ class ContextSlide extends React.Component {
...
+        <div className="wrapper">
+
+          <div className="container__row">
+            <div className="container__block">
+              <h2 className="heading -beta">Woohoo! You're signed up.</h2>
+              <p>Nice! By joining [campaign name] campaign, you've teamed up with 5.4 million other members who are making an impact on the causes affecting your world.</p>
+              <p>As a DoSomething.org member, you're part of something bigger. You're part of a global movement for good.</p>
+
+              <h2 className="heading -beta">Campaigns are a way to make impact.</h2>
+              <p>You'll get all the tolls you need to create impact. You've already joing [campaign name]. Now sign up for other popular campaigns!</p>
```
Comment (DFurnes) [inline lib/themes/dosomething/paraneue_dosomething/js/components/ContextSlide.js]: tolls → tools 🔨

File: lib/themes/dosomething/paraneue_dosomething/scss/content/_onboarding.scss [hunk 3]
```diff
@@ -1,4 +1,82 @@
...
   color: #fff;
+  position: relative;
+
+  > .wrapper {
+    padding: $base-spacing 0 $section-spacing;
+  }
+}
+
+// @TODO: maybe this close button should be a pattern
+// since it is used in the modal and this onboarding component?
```
Comment (DFurnes) [inline lib/themes/dosomething/paraneue_dosomething/scss/content/_onboarding.scss:12]: Yeah, that seems like a pretty good idea. 👍

File: lib/themes/dosomething/paraneue_dosomething/scss/content/_onboarding.scss [hunk 4]
```diff
@@ -1,4 +1,82 @@
...
+}
+
+.slideshow__controller {
+  display: table;
+  margin: 0 auto;
+  min-height: 41px;
+  padding: 0 ($base-spacing / 2);
+  position: relative;
+
+  > ul {
```
Comment (DFurnes) [inline lib/themes/dosomething/paraneue_dosomething/scss/content/_onboarding.scss:55]: It might make sense to give these elements their own child classnames or make them their own standalone elements, so it's not so tightly coupled to a particular DOM hierarchy?

File: lib/themes/dosomething/paraneue_dosomething/scss/content/_onboarding.scss [hunk 5]
```diff
@@ -1,4 +1,82 @@
...
+    overflow: hidden;
+
+    > li {
+      float: left;
+      padding: 0 5px;
+    }
+  }
+
+
+  > button {
```
Comment (DFurnes) [inline lib/themes/dosomething/paraneue_dosomething/scss/content/_onboarding.scss:66]: This feels like it should be a new modifier for `.button`.

File: lib/themes/dosomething/paraneue_dosomething/js/components/ContextSlide.js (hunk 1 above)
Comment (weerd) [inline lib/themes/dosomething/paraneue_dosomething/js/components/ContextSlide.js]: Yeah, I'll switch it to it's own `slideshow__slide` wrapping element. I was just starting to feel a strong case of divitis coming on ;)

File: lib/themes/dosomething/paraneue_dosomething/js/components/ContextSlide.js (hunk 2 above)
Comment (weerd) [inline lib/themes/dosomething/paraneue_dosomething/js/components/ContextSlide.js]: totes meant "tolls". Fact... more "tolls" equals more impact. :trollface:

File: lib/themes/dosomething/paraneue_dosomething/scss/content/_onboarding.scss (hunk 5 above)
Comment (weerd) [inline lib/themes/dosomething/paraneue_dosomething/scss/content/_onboarding.scss:66]: Yeah, defs. I can do that for next PR. Added a `@TODO` :)

File: lib/themes/dosomething/paraneue_dosomething/scss/content/_onboarding.scss (hunk 4 above)
Comment (weerd) [inline lib/themes/dosomething/paraneue_dosomething/scss/content/_onboarding.scss:55]: Yeah, I did initially and then hated the class name/ super-long BEM name. I can make this another "next PR" update too.
